apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-api
  template:
    metadata:
      labels:
        app: hello-api
    spec:
      containers:
      - name: app
        image: docker.io/codeform/hello-api
        env:
        - name: ADDR
          value: :8080
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: greeter-app
              key: greeting
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-api
spec:
  selector:
    app: hello-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
